# Generated by Django 4.2.3 on 2023-11-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_person_firstname_remove_person_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='firstname',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='lastname',
            field=models.CharField(default='aaaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='ssss', max_length=100),
            preserve_default=False,
        ),
    ]
